
CREATE TABLE user 
(
    ID INTEGER NOT NULL,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    USERNAME VARCHAR(255),
    PRIMARY KEY (ID)
) ENGINE=InnoDB